version: '3.4'
networks:
  all:
    driver: bridge
  cliente-network:
    driver: bridge
services:
  devsu-test:
    container_name: devsu-test
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      ENVIRONMENT: production
      DB_NAME: clientes
      DB_HOST: test_db
      DB_PORT: 5433
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      test_db:
        condition: service_healthy
    networks:
      - all
      - cliente-network
  test_db:
    container_name: test_db
    build:
      context: .
      dockerfile: database.dockerfile
    ports:
      - "5433:5433"
    environment:
      POSTGRES_DB: clientes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 5s
      retries: 5
    networks:
      - cliente-network